# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Label pull request
on: [pull_request_target]

jobs:
  add_label:
    runs-on: ubuntu-22.04
    if: github.repository == 'microsoft/semantic-kernel'
    timeout-minutes: 1
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Label prs
        uses: actions/labeler@ac9175f
        with:
          repo-token: "${{ secrets.GH_ACTIONS_PR_WRITE }}"
