# Run ruff and black checks.
name: Python Lint
on:
  workflow_dispatch:
  pull_request:
    branches: ["main", "feature*"]
    paths:
      - 'python/**'

jobs:
  ruff:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions: {}
    steps:
      - name: Add var to GITHUB_PATH
        run: echo "/root/.local/bin" >> $GITHUB_PATH
      - name: Checkout repository
        uses: actions/checkout@9bb5618
      - name: Install poetry
        run: pipx install poetry==1.8.2
      - name: Setup python
        uses: action/setup-python@82c7e63
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Install Semantic Kernel
        working-directory: ./python
        run: poetry install --no-ansi
      - name: Run lint
        working-directory: ./python
        run: poetry run ruff check .
  black:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions: {}
    steps:
      - name: Add var to GITHUB_PATH
        run: echo "/root/.local/bin" >> $GITHUB_PATH
      - name: Checkout repository
        uses: actions/checkout@9bb5618
      - name: Install poetry
        run: pipx install poetry==1.8.2
      - name: Setup python
        uses: action/setup-python@82c7e63
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Install Semantic Kernel
        working-directory: ./python
        run: poetry install --no-ansi
      - name: Run lint
        working-directory: ./python
        run: poetry run black --check .
