name: Python Unit Tests

on:
  pull_request:
    branches: ["main", "feature*"]
    paths:
      - "python/**"

jobs:
  python-unit-tests:
    name: Python Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    permissions:
      contents: write
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@9bb5618
      - name: Install poetry
        run: pipx install poetry==1.8.2
      - name: Set up Python ${{ matrix.python-version }}
        uses: action/setup-python@82c7e63
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Install dependencies
        working-directory: ./python
        run: poetry install --with unit-tests
      - name: Test with pytest
        working-directory: ./python
        run: poetry run pytest -q --junitxml=pytest-${{ matrix.os }}-${{ matrix.python-version }}.xml  --cov=semantic_kernel --cov-report=term-missing:skip-covered ./tests/unit | tee python-coverage-${{ matrix.os }}-${{ matrix.python-version }}.txt
      - name: Upload coverage
        uses: actions/upload-artifact@a8a3f3a
        if: github.repository == 'microsoft/semantic-kernel'
        with:
          name: python-coverage-${{ matrix.os }}-${{ matrix.python-version }}.txt
          path: python/python-coverage-${{ matrix.os }}-${{ matrix.python-version }}.txt
          overwrite: true
          retention-days: 1
      - name: Upload pytest.xml
        uses: actions/upload-artifact@a8a3f3a
        if: github.repository == 'microsoft/semantic-kernel'
        with:
          name: pytest-${{ matrix.os }}-${{ matrix.python-version }}.xml
          path: python/pytest-${{ matrix.os }}-${{ matrix.python-version }}.xml
          overwrite: true
          retention-days: 1
