# Build wheel for projet and upload.
name: python-build-wheel

on:
  workflow_dispatch:
  push:
    branches: ["python_preview"]

permissions:
  contents: read

jobs:
  build-wheel:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    defaults:
      run:
        working-directory: python

    steps:
      - name: Checkout repository
        uses: actions/checkout@9bb5618

      - name: Add var to GITHUB_PATH
        run: echo "/root/.local/bin" >> $GITHUB_PATH

      - name: Install poetry
        run: pipx install poetry==1.8.2

      - name: Set up Python
        uses: action/setup-python@82c7e63
        with:
          python-version: '3.10'
          cache: "poetry"
          cache-dependency-path: "python/pyproject.toml"

      - name: Install Semantic Kernel
        run: poetry install --no-ansi

      - name: Build wheel
        run: poetry build

      - name: Upload wheel file to artifacts
        if: github.repository == 'microsoft/semantic-kernel'
        uses: actions/upload-artifact@a8a3f3a
        with:
          name: dist
          path: python/dist/*
