# Check pull requests for typos.
#
# Configuration: .github/_typos.toml
#
# Info:          https://github.com/marketplace/actions/typos-action
# Local install: brew install typos-cli
# Local install: conda install typos
# Local run:     typos -c .github/_typos.toml

name: Spell Check

on:
  workflow_dispatch:
  pull_request:
    branches: ["main", "java-development", "feature*"]

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    permissions: {}
    steps:
      - name: Check out code
        uses: actions/checkout@9bb5618

      - name: Use custom config file
        uses: crate-ci/typos@c15b28f
        with:
          config: .github/_typos.toml
          write_changes: false
